spring.datasource.url=jdbc:mariadb://localhost:3307/fancollector_dev?serverTimezone=UTC
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.username=fancollector_user
spring.datasource.password=fancollector_pass

spring.jpa.hibernate.ddl-auto=update

jwt.secret=CLAVE_SUPER_SECRETA_Y_TAMBIEN_SUPER_LARGA
jwt.expiration=10000

cloudinary.cloud-name=df6igq4wp
cloudinary.api-key=898897471764715
cloudinary.api-secret=C1um-A9rpWMZGwW1rL58EW0PfGk
cloudinary.folder=fancollector-desarrollo
